### PR TITLE
Adding Sources to Positions

### PR DESCRIPTION
**Pull request by vahurtad**
* adds another screen for full screen WebView Content 
* adds navigation to WebView Content
* adds a loading indicator 
* changes IssueCard Touchable to arrow instead of container

### CODE REVIEW

**Comment by vahurtad** [comment]
screenshot_20181021-204447

**Comment by vahurtad** [comment]
screenshot_20181021-204447

**Comment by vahurtad** [comment]
screenshot_20181021-204447

**Review by mialknowles — APPROVED** [review]

**Review by vahurtad — COMMENTED** [review]
There was a conflict from last PR merge on yarn.lock that was not resolved which doubled the lines. Resolving it with this PR!

**Review by mialknowles — APPROVED** [review]

**Review by crieggalder — APPROVED** [review]

**Pull request merged**
